"""Trying smth

Revision ID: 41f1b4699596
Revises: 8f6c2e11043d
Create Date: 2024-06-08 01:33:07.656699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41f1b4699596'
down_revision = '8f6c2e11043d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_2fa_enabled', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('secret_token', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('secret_token')
        batch_op.drop_column('is_2fa_enabled')

    # ### end Alembic commands ###
