"""Trying smth

Revision ID: 439c31457df2
Revises: d6bd87d8515c
Create Date: 2024-06-08 03:15:00.260102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '439c31457df2'
down_revision = 'd6bd87d8515c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_used', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('qr_used')

    # ### end Alembic commands ###
