"""Trying smth

Revision ID: 86a0dd876e7f
Revises: 41f1b4699596
Create Date: 2024-06-08 02:44:01.190870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86a0dd876e7f'
down_revision = '41f1b4699596'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_approved_code', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('qr_approved_code_expire', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('qr_approved_code_expire')
        batch_op.drop_column('qr_approved_code')

    # ### end Alembic commands ###
