"""Trying smth

Revision ID: 8f6c2e11043d
Revises: c9817dc51cdf
Create Date: 2024-06-08 01:31:39.113941

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8f6c2e11043d'
down_revision = 'c9817dc51cdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verify_token_expire', sa.DateTime(), nullable=True))
        batch_op.drop_column('email_verify_token_created')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verify_token_created', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('email_verify_token_expire')

    # ### end Alembic commands ###
