"""Trying something

Revision ID: c9817dc51cdf
Revises: e3554a00aeb3
Create Date: 2024-06-08 00:53:08.326019

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c9817dc51cdf'
down_revision = 'e3554a00aeb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chapters')
    op.drop_table('comic')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verify_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('email_verify_token_created', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email_verify_token_created')
        batch_op.drop_column('email_verify_token')

    op.create_table('comic',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('cover', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('publisher_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['publisher_id'], ['user.id'], name='comic_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('chapters',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('comic_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('translator_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('redactor_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cleaner_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('typesetter_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('proofreader_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chapter', mysql.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['cleaner_id'], ['user.id'], name='chapters_ibfk_4'),
    sa.ForeignKeyConstraint(['comic_id'], ['comic.id'], name='chapters_ibfk_1'),
    sa.ForeignKeyConstraint(['proofreader_id'], ['user.id'], name='chapters_ibfk_6'),
    sa.ForeignKeyConstraint(['redactor_id'], ['user.id'], name='chapters_ibfk_3'),
    sa.ForeignKeyConstraint(['translator_id'], ['user.id'], name='chapters_ibfk_2'),
    sa.ForeignKeyConstraint(['typesetter_id'], ['user.id'], name='chapters_ibfk_5'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
